mysite/blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/', views.PostView.as_view(), name='posts'),
    path('posts/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('posts/create_comment', views.create_comment, name='create_comment'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

mysite/blog/models.py
from django.db import models

from django.utils import timezone


# Create your models here.
class Post(models.Model):
    user = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=100000)
    pub_date = models.DateTimeField('publishing date', default=timezone.now())

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.CharField(max_length=20)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.CharField(max_length=255)
    pub_date = models.DateTimeField('publishing date', default=timezone.now())
    

    def __str__(self):
        return self.body

mysite/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Required")
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .forms import RegistrationForm

from .models import Post, Comment

# Create your views here.
class IndexView(generic.ListView):
    template_name = "blog/index.html"

    def get_queryset(self):
        return None
    

class PostView(generic.ListView):
    template_name = "blog/posts.html"
    context_object_name = "latest_post_list"

    def get_queryset(self):
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Post
    template_name = "blog/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(post=context["post"]) 
        return context

    def get_queryset(self):
        return Post.objects.filter(pub_date__lte=timezone.now())

class RegisterView(generic.edit.FormView):
    form_class = RegistrationForm
    success_url = "blog/login/"
    template_name = "registration/register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterView, self).form_valid(form)
    
    def form_invalid(self, form):
        return super(RegisterView, self).form_invalid(form)


def create_comment(request):
    return redirect("/posts")

mysite/blog/templates/blog/detail.html
{% extends 'blog/navbar.html' %}

{% block page_header %}
<h1>Заглавие: {{ post.title }}</h1>
<div class='autor'>Автор сообщения:</div><div class='autor_s'>{{ post.user }}</div>
<div class='date'>Дата публикации:</div><div class='pub_date'>{{post.pub_date|date:'M d, Y'}}</div>
{% endblock page_header %}
{% block content %}
<h1>Текст:</h1>
<div class='post'>{{ post.body }}</div></big></big>
      <h3>Комментарии:</h3>
      {% if comments %}
          {% for comment in comments %}
            <div class="card" style="width: 500px; margin-top: 20px;">
              <div class="card-body">
                <h5 class="card-title">{{ comment.user }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ comment.pub_date }}</h6>
                <p class="card-text">{{ comment }}</p>
              </div>
            </div>
          {% endfor %}
      {% else %}
      <p>Комментарии отсутствуют</p>
      {% endif %}
    </div>
    <div>
      <form action="{% url 'blog:create_comment' %}" method="post">
        {% csrf_token %}
        <div class='date'><h3>Оставить комментарий:</h3></div>
        <div>
          <input type=”text” placeholder="Ваше имя" size="32" style="width: 150; margin-bottom: 2px;">
        </div>
        <textarea placeholder="Комментарий" maxlength="100" cols="35" rows="3" style="resize: none;"></textarea>
        <input type="submit" value="Оставить комментарий" class="btn btn-primary" style="display: block;">
      </form>
    </div>
  </div>

  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}
  
{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/navbar.html' %}

{% block page_header %}

<div class="jumbotron">
  <h1 class="display-4">Информация обо мне</h1>
  <marquee behavior="alternate" direction="right">Тут должен быть текст</marquee>
</div>
{% endblock page_header %}

mysite/blog/templates/blog/navbar.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Блог</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'blog:index'%}">Домашняя страница</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse-2">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'blog:posts'%}">Блоги</a></li>
          <li><a href="http://127.0.0.1:8000/admin/" title="redmouse 12345678">Администрирование</a></li>
          <li><a href="{% url 'blog:register'%}">Регистрация</a></li>
          {% if user.is_authenticated %}
          <li>
            <a class="nav navbar-nav navbar-right" data-toggle="dropdown" role="button" aria-expanded="false"><img class="img-circle" src="https://bootstraptema.ru/snippets/icons/2016/mia/1.png" alt="USER" width="20" />{{ user.username }}<span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><a class="dropdown-item" href="{% url 'blog:logout' %}">Logg out</a></li>
            </ul>
          </li>
          {% else %}
          <a class="btn btn-default btn-outline btn-circle" data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Вход</a>
        </ul>
        <div class="collapse nav navbar-nav nav-collapse" id="nav-collapse2">
          <form class="navbar-form navbar-right form-inline" role="form">
            <div class="form-group">
              <label class="sr-only">Email</label>
              <input class="form-control" id="Email" placeholder="Логин" autofocus required />
            </div>
            <div class="form-group">
              <label class="sr-only" for="Password">Password</label>
              <input type="password" class="form-control" id="Password" placeholder="Пароль" required />
            </div>
            <div class="form-group">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ form|crispy }}
                <button type="submite" class="btn btn-success">Вход</button>
              </form>
            </div>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</html>

mysite/blog/templates/blog/posts.html
{% extends 'blog/navbar.html' %}

{% block page_header %}
  <h1>Посты</h1>
{% endblock page_header %}
{% block content %}
    {% for post in latest_post_list %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h4 class="card-header">
          <div><a href="{% url 'blog:detail' post.id %}">{{ post }}</a></div> 
          <div style="float: right;">{{ post.user }}: {{ post.pub_date|date:'M d, Y' }}</div>
        </h4>
        <div class="card-body">
          {{ post.body|truncatechars:100 }}
          <div style="margin-top: 20px;"><a class="btn btn-primary" href="{% url 'blog:detail' post.id %}" role="button">Информация</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
{% endblock content %}